x-common-variables: &common-env
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Toronto

x-common-logging: &common-logging
  logging:
    driver: json-file

x-common-restart-policy: &restart-policy
  restart: always

services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    <<: 
      - *restart-policy
      - *common-logging
      - *common-env
    ports:
      - 7878:7878
    volumes:
      - ${BASE_DIR:-/data}/appdata/radarr:/config
      - ${BASE_DIR:-/data}:/data
    networks:
      - media_network

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    <<: 
      - *restart-policy
      - *common-logging
      - *common-env
    ports:
      - 8989:8989
    volumes:
      - ${BASE_DIR:-/data}/appdata/sonarr:/config
      - ${BASE_DIR:-/data}:/data
    networks:
      - media_network

  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    <<: 
      - *restart-policy
      - *common-logging
      - *common-env
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ${BASE_DIR:-/data}/appdata/nzbget:/config
      - ${BASE_DIR:-/data}/usenet:/data/usenet:rw
    networks:
      - media_network

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    <<: 
      - *restart-policy
      - *common-logging
      - *common-env
    ports:
    # https://jellyfin.org/docs/general/networking/
      - 8096:8096
      - 1900:1900/udp # DLNA
      - 7359:7359/udp # DLNA
    volumes:
      - ${BASE_DIR:-/data}/appdata/jellyfin:/config
      - ${BASE_DIR:-/data}:/data
    networks:
      - media_network

  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    <<: 
      - *restart-policy
      - *common-logging
      - *common-env
    ports:
      - 5055:5055
    volumes:
      - ${BASE_DIR:-/data}/appdata/jellyseerr:/config
      - ${BASE_DIR:-/data}:/data
    networks:
      - media_network
  
  caddy:
    container_name: caddy
    image: caddy:2.9
    <<: 
      - *restart-policy
      - *common-logging
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      # https://hub.docker.com/_/caddy
      - $PWD/conf:/etc/caddy
      # Caddy does not need to share a filesyetm with the services it proxies
      # Let docker handle the named volumes
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - media_network

networks:
  media_network:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
